version: '3.8'

networks:
  i2i-network:
    driver: bridge

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-backend-db
    ports:
      - "1533:1521"
    environment:
      - ORACLE_PASSWORD=mysecurepassword
      - APP_USER=i2i_user
      - APP_USER_PASSWORD=i2i_password  # <-- İşte burayı tam istendiği gibi düzelttik!
    networks:
      - i2i-network
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: